// Golden-vector generator: the JS sim is the REFERENCE; this emits native/golden.h
// for the C cross-validation harness. Regenerate whenever the JS physics changes:
//   node native/gen-golden.mjs
import { writeFileSync } from 'node:fs';
import {
  stepAircraft, initialState, groundState, forcesMoments, TRIM, AC,
} from '../src/physics.js';
import { createWind, stepWind } from '../src/wind.js';
import { defaultParams } from '../src/params.js';

const DT = 1 / 60;
const f = (x) => Number(x).toPrecision(17);
const arr = (a) => a.map(f).join(', ');

// --- A) point-wise forces/moments at hand-picked states -------------------------
const points = [];
const mkState = (pos, vel, quat, omega, act) => ({ pos, vel, quat, omega, act });
const norm = (q) => { const n = Math.hypot(...q); return q.map((v) => v / n); };
const cases = [
  mkState([0, 120, 0], [0, 0, -30], norm([0.0278, 0, 0, 0.9996]), [0, 0, 0], { da: 0, de: TRIM.de, dr: 0, dt: TRIM.dt }),
  mkState([50, 300, -400], [3, -2, -33], norm([0.05, 0.1, -0.2, 0.97]), [0.1, -0.05, 0.2], { da: 0.1, de: -0.15, dr: 0.05, dt: 0.8 }),
  mkState([0, 15, 100], [1, 1, -22], norm([0.12, 0.02, 0.03, 0.99]), [-0.2, 0.1, -0.1], { da: -0.2, de: 0.1, dr: -0.1, dt: 0.3 }),
  mkState([0, 2000, 0], [0, 0, -38], norm([0.02, 0, 0, 1]), [0, 0, 0], { da: 0, de: TRIM.de, dr: 0, dt: 0.9 }),
];
const winds = [[0, 0, 0], [3, -1, 5], [-8, 0, 0], [0, 2, -4]];
for (let i = 0; i < cases.length; i++) {
  const s = cases[i];
  const { F, M, Va, alpha, beta } = forcesMoments(s.quat, s.vel, s.omega, s.act, s.pos[1], winds[i]);
  points.push({ s, wind: winds[i], F, M, Va, alpha, beta });
}

// --- B) trajectories (sampled every second) -------------------------------------
function trajectory(boot, cmdsAt, seconds, env) {
  let s = boot === 'air' ? initialState() : { ...groundState(), pos: [0, 0, 0] };
  let w = createWind(2);
  const P = { ...defaultParams(), WND_N_MS: env.n, WND_E_MS: env.e, WND_TRB: env.trb };
  const samples = [];
  for (let i = 0; i < seconds * 60; i++) {
    const sw = stepWind(w, s, P, DT);
    w = sw.wind;
    s = stepAircraft(s, cmdsAt(i), DT, sw.windWorld);
    if ((i + 1) % 60 === 0) samples.push([...s.pos, ...s.vel, ...s.quat, ...s.omega, s.act.da, s.act.de, s.act.dr, s.act.dt]);
  }
  return samples;
}
const TRIM_CMD = { aileron: 0, elevator: TRIM.de / AC.maxDef, rudder: 0, throttle: TRIM.dt };
const trajs = [
  { name: 'trim_calm', boot: 'air', env: { n: 0, e: 0, trb: 0 }, seconds: 30, cmds: () => TRIM_CMD },
  {
    name: 'doublets_turb', boot: 'air', env: { n: -5, e: 3, trb: 1.5 }, seconds: 20,
    cmds: (i) => ({
      aileron: i >= 300 && i < 360 ? 0.3 : 0,
      elevator: TRIM.de / AC.maxDef + (i >= 600 && i < 660 ? -0.2 : 0),
      rudder: i >= 900 && i < 960 ? 0.2 : 0,
      throttle: TRIM.dt,
    }),
  },
  { name: 'ground_roll', boot: 'ground', env: { n: 0, e: 0, trb: 0 }, seconds: 8, cmds: () => ({ aileron: 0, elevator: 0, rudder: 0, throttle: 1 }) },
];
const trajData = trajs.map((t) => ({ ...t, samples: trajectory(t.boot, t.cmds, t.seconds, t.env) }));

// --- emit golden.h ----------------------------------------------------------------
let h = `/* AUTO-GENERATED by native/gen-golden.mjs — do not edit. JS is the reference. */
#ifndef GOLDEN_H
#define GOLDEN_H
#define N_POINTS ${points.length}
`;
h += `static const double GP_STATE[N_POINTS][17] = {\n${points.map(({ s }) =>
  `  {${arr([...s.pos, ...s.vel, ...s.quat, ...s.omega, s.act.da, s.act.de, s.act.dr, s.act.dt])}}`).join(',\n')}\n};\n`;
h += `static const double GP_WIND[N_POINTS][3] = {\n${points.map((p) => `  {${arr(p.wind)}}`).join(',\n')}\n};\n`;
h += `static const double GP_OUT[N_POINTS][9] = {\n${points.map((p) =>
  `  {${arr([...p.F, ...p.M, p.Va, p.alpha, p.beta])}}`).join(',\n')}\n};\n`;

trajData.forEach((t, ti) => {
  h += `#define T${ti}_N ${t.samples.length}\n`;
  h += `static const double T${ti}_SAMPLES[T${ti}_N][17] = {\n${t.samples.map((row) => `  {${arr(row)}}`).join(',\n')}\n};\n`;
});
h += `static const double TRAJ_ENV[3][3] = {\n${trajData.map((t) => `  {${arr([t.env.n, t.env.e, t.env.trb])}}`).join(',\n')}\n};\n`;
h += '#endif\n';
writeFileSync(new URL('./golden.h', import.meta.url), h);
console.log(`golden.h: ${points.length} point cases, ${trajData.map((t) => `${t.name}(${t.samples.length})`).join(', ')}`);
