// FMI 2.0 modelDescription.xml generator + FMU packager.
//   node gen-fmu.mjs          → writes fmu-build/modelDescription.xml
//   node gen-fmu.mjs --pack   → also zips fmu-build/ into fdm-uav.fmu
//
// channels.json is the single source of truth (shared with the VeriStand wrapper
// and INTERFACE.md). Value references: inputs 0..N-1, outputs 100.., matching the
// enum in fmi2_model.c — this generator VERIFIES that mapping and fails on drift.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';

const here = (p) => new URL(p, import.meta.url);
const ch = JSON.parse(readFileSync(here('./channels.json')));
const OUT_BASE = 100;
const PARAM_BASE = 200;

// --- consistency gate: C enum order must match channels.json ---------------------
const csrc = readFileSync(here('./fmi2_model.c'), 'utf8');
function enumOrder(afterMarker) {
  // collect VR_* identifiers in declaration order, dropping *_COUNT/*_BASE sentinels
  const start = csrc.indexOf(afterMarker);
  const block = csrc.slice(start, csrc.indexOf('}', start));
  return [...block.matchAll(/VR_([A-Z_]+)/g)].map((m) => m[1])
    .filter((t) => t !== 'IN_COUNT' && t !== 'OUT_BASE');
}
const inEnum = enumOrder('enum {\n  VR_CMD_A');
const outEnum = enumOrder('enum {\n  VR_POS_N');
// Map channels.json names → expected enum tokens.
const tok = (n) => n.toUpperCase()
  .replace('CMD_AILERON', 'CMD_A').replace('CMD_ELEVATOR', 'CMD_E')
  .replace('CMD_RUDDER', 'CMD_R').replace('CMD_THROTTLE', 'CMD_T')
  .replace('ENV_WINDN', 'ENV_N').replace('ENV_WINDE', 'ENV_E').replace('ENV_TURB', 'ENV_TURB')
  .replace('FLT_AILERON', 'FLT_A').replace('FLT_ELEVATOR', 'FLT_E')
  .replace('FLT_RUDDER', 'FLT_R').replace('FLT_THROTTLE', 'FLT_T')
  .replace('SIM_RESET', 'RESET')
  .replace('POS_N', 'POS_N').replace('POS_E', 'POS_E').replace('POS_D', 'POS_D')
  .replace('VEL_N', 'VEL_N').replace('VEL_E', 'VEL_E').replace('VEL_D', 'VEL_D')
  .replace('ATT_ROLL', 'ATT_ROLL').replace('ATT_PITCH', 'ATT_PITCH').replace('ATT_YAW', 'ATT_YAW')
  .replace('RATE_P', 'RATE_P').replace('RATE_Q', 'RATE_Q').replace('RATE_R', 'RATE_R')
  .replace('AIR_VA', 'AIR_VA').replace('AIR_ALPHA', 'AIR_ALPHA').replace('AIR_BETA', 'AIR_BETA')
  .replace('ACT_AILERON', 'ACT_A').replace('ACT_ELEVATOR', 'ACT_E')
  .replace('ACT_RUDDER', 'ACT_R').replace('ACT_THROTTLE', 'ACT_T')
  .replace('WOW', 'WOW');
const inTokens = ch.inports.map((c) => tok(c.name));
const outTokens = ch.outports.map((c) => tok(c.name));
if (JSON.stringify(inTokens) !== JSON.stringify(inEnum)) {
  console.error(`INPUT vref mismatch:\n  C enum:  ${inEnum}\n  json:    ${inTokens}`);
  process.exit(1);
}
if (JSON.stringify(outTokens) !== JSON.stringify(outEnum)) {
  console.error(`OUTPUT vref mismatch:\n  C enum:  ${outEnum}\n  json:    ${outTokens}`);
  process.exit(1);
}

// --- consistency gate 2: fdm_coef field order (fdm.h) must match "parameters" ----
const hdr = readFileSync(here('./fdm.h'), 'utf8');
const coefBlock = hdr.match(/typedef struct \{([^}]*)\} fdm_coef;/s)[1];
const coefFields = [...coefBlock.matchAll(/\b([A-Za-z_][A-Za-z0-9_]*)\b(?=[,;])/g)]
  .map((m) => m[1]).filter((t) => t !== 'double');
const paramNames = ch.parameters.map((p) => p.name);
if (JSON.stringify(coefFields) !== JSON.stringify(paramNames)) {
  console.error(`PARAMETER order mismatch:\n  fdm_coef: ${coefFields}\n  json:     ${paramNames}`);
  process.exit(1);
}

// --- emit modelDescription.xml ---------------------------------------------------
const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const scalar = (c, vr, causality, start) => {
  const attrs = [`name="${c.name}"`, `valueReference="${vr}"`, `causality="${causality}"`,
    `variability="${causality === 'output' ? 'continuous' : 'discrete'}"`, `description="${esc(c.desc)}"`];
  const real = causality === 'input'
    ? `<Real start="${start ?? 0}"${c.min !== undefined ? ` min="${c.min}" max="${c.max}"` : ''}/>`
    : `<Real/>`;
  return `    <ScalarVariable ${attrs.join(' ')}>\n      ${real}\n    </ScalarVariable>`;
};

const vars = [];
ch.inports.forEach((c, i) => vars.push(scalar(c, i, 'input', c.name === 'Cmd_Throttle' ? 0 : 0)));
ch.outports.forEach((c, i) => vars.push(scalar(c, OUT_BASE + i, 'output')));
ch.parameters.forEach((c, i) => vars.push(
  `    <ScalarVariable name="${c.name}" valueReference="${PARAM_BASE + i}" causality="parameter" variability="tunable" description="${esc(c.desc)}">\n      <Real start="${c.default}"/>\n    </ScalarVariable>`
));
const outputIdx = ch.outports.map((_, i) => `      <Unknown index="${ch.inports.length + i + 1}"/>`).join('\n');

const guid = 'FDM-UAV-FMI2-' + ch.inports.length + 'x' + ch.outports.length;
const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED by native/gen-fmu.mjs from channels.json. Do not edit. -->
<fmiModelDescription
  fmiVersion="2.0"
  modelName="${ch.model}"
  guid="${guid}"
  description="${esc(ch.description)}"
  generationTool="flight-sim-fable5 (golden-validated against the JS reference)"
  numberOfEventIndicators="0">
  <CoSimulation
    modelIdentifier="${ch.model}"
    canHandleVariableCommunicationStepSize="true"
    canBeInstantiatedOnlyOncePerProcess="false"/>
  <DefaultExperiment startTime="0.0" stepSize="${(1 / ch.base_rate_hz).toPrecision(9)}"/>
  <ModelVariables>
${vars.join('\n')}
  </ModelVariables>
  <ModelStructure>
    <Outputs>
${outputIdx}
    </Outputs>
  </ModelStructure>
</fmiModelDescription>
`;

mkdirSync(here('./fmu-build/binaries/linux64'), { recursive: true });
writeFileSync(here('./fmu-build/modelDescription.xml'), xml);
console.log(`modelDescription.xml: ${ch.inports.length} inputs, ${ch.outports.length} outputs, ${ch.parameters.length} parameters (vref + fdm_coef order verified)`);

if (process.argv.includes('--pack')) {
  const so = here('./fmu-build/binaries/linux64/' + ch.model + '.so');
  if (!existsSync(so)) { console.error('build the .so first: make fmu-so'); process.exit(1); }
  const dir = here('./fmu-build').pathname;
  const fmu = here('./' + ch.model + '.fmu').pathname;
  execSync(`cd "${dir}" && zip -r -X "${fmu}" modelDescription.xml binaries >/dev/null`);
  console.log(`packed: ${ch.model}.fmu`);
}
